%% DRISHTI Master Simulation Engine
% Coordinated multi-drone disaster response loop integrating kinematics,
% explainable decision support, route optimization, and atomic JSON broadcasting.
%
% Usage:
% >> drishti_master_simulation

function drishti_master_simulation()
    clear; clc;
    fprintf('=======================================================\n');
    fprintf('   DRISHTI: MASTER DISASTER SIMULATION (MODULAR)       \n');
    fprintf('=======================================================\n');

    currentFolder = fileparts(mfilename('fullpath'));
    projectRoot = fileparts(currentFolder);
    outputDir = fullfile(projectRoot, 'public', 'data');
    if ~exist(outputDir, 'dir'); mkdir(outputDir); end
    outputFile = fullfile(outputDir, 'rescue_results.json');
    tempFile = fullfile(outputDir, 'rescue_results_temp.json');

    dt = 1.0;
    loopDelay = 1.5;
    step = 0;
    blockageStep = 18;
    rescuedCount = 0;

    % Initial fleet state
    drones = struct(...
        'id', {1, 2, 3, 4, 5}, ...
        'name', {'DRONE-01', 'DRONE-02', 'DRONE-03', 'DRONE-04', 'DRONE-05'}, ...
        'x', {700, -420, 1160, 100, 980}, ...
        'y', {700, 1120, -460, 0, 1480}, ...
        'altitude', {100, 100, 100, 100, 100}, ...
        'speed', {10, 12, 11, 10, 13}, ...
        'battery', {90, 85, 80, 95, 75}, ...
        'available', {true, true, true, true, true}, ...
        'status', {'SEARCHING', 'SEARCHING', 'SEARCHING', 'SEARCHING', 'SEARCHING'}, ...
        'vx', {6, -5, 7, 4, -6}, ...
        'vy', {5, 6, -4, 8, -5} ...
    );

    % Initial casualties
    victims = struct(...
        'id', {1, 2, 3}, ...
        'name', {'V-1', 'V-2', 'V-3'}, ...
        'x', {650, 250, 800}, ...
        'y', {750, 450, 250}, ...
        'priority', {'HIGH', 'MEDIUM', 'LOW'}, ...
        'status', {'ASSIGNED', 'DETECTED', 'DETECTED'}, ...
        'assignedDrone', {2, 0, 0}, ...
        'rescueTimer', {0, 0, 0} ...
    );

    fprintf('Master simulation loop active. Writing to: %s\n', outputFile);
    fprintf('Press Ctrl+C to terminate simulation.\n\n');

    while true
        step = step + 1;
        timestamp = datestr(now, 'yyyy-mm-dd HH:MM:SS');

        % 1. Victim Triage & Target Selection
        [victims, targetVictim] = victim_simulation(victims, 2);

        % 2. Multi-Criteria Scoring for Drone Selection
        bestDroneIdx = 1;
        highestScore = -Inf;
        scores = zeros(1, numel(drones));
        for i = 1:numel(drones)
            dist = sqrt((drones(i).x - targetVictim.x)^2 + (drones(i).y - targetVictim.y)^2);
            f_dist = max(0, 1 - (dist / 3000));
            f_bat = drones(i).battery / 100;
            f_spd = drones(i).speed / 15;
            f_avail = double(drones(i).available && drones(i).battery > 15);
            score = (0.45 * f_dist) + (0.25 * f_bat) + (0.15 * f_spd) + (0.15 * f_avail);
            if drones(i).battery <= 15; score = score * 0.05; end
            scores(i) = score;
            if score > highestScore
                highestScore = score;
                bestDroneIdx = i;
            end
        end
        assignedDrone = drones(bestDroneIdx);

        % 3. Drone Kinematics Update
        drones = drone_simulation(drones, dt, targetVictim);

        % 4. Road Blockage Simulation
        roadBlocked = (step >= blockageStep && step < (blockageStep + 25));
        selectedRoute = 'fastest';
        if roadBlocked; selectedRoute = 'alternative'; end

        assignedDistance = sqrt((assignedDrone.x - targetVictim.x)^2 + (assignedDrone.y - targetVictim.y)^2);
        estArrivalSec = round(assignedDistance / max(assignedDrone.speed, 1));

        % 5. Build Export Structure
        dronesExport = cell(1, numel(drones));
        for i = 1:numel(drones)
            dronesExport{i} = struct('id', drones(i).id, 'name', drones(i).name, ...
                'x', round(drones(i).x, 1), 'y', round(drones(i).y, 1), ...
                'altitude', drones(i).altitude, 'speed', drones(i).speed, ...
                'battery', round(drones(i).battery, 1), 'available', drones(i).available, ...
                'status', drones(i).status);
        end

        victimsExport = cell(1, numel(victims));
        for v = 1:numel(victims)
            victimsExport{v} = struct('id', victims(v).id, 'name', victims(v).name, ...
                'x', victims(v).x, 'y', victims(v).y, 'priority', victims(v).priority, ...
                'status', victims(v).status, 'assignedDrone', victims(v).assignedDrone);
        end

        outputStruct = struct(...
            'drones', {dronesExport}, ...
            'victims', {victimsExport}, ...
            'rescue', struct('target_victim', targetVictim.id, 'priority', targetVictim.priority, ...
                             'assigned_drone', assignedDrone.id, 'distance', round(assignedDistance, 2), ...
                             'battery', round(assignedDrone.battery, 1)), ...
            'decision_support', struct('selected_drone_id', assignedDrone.id, 'target_victim_id', targetVictim.id, ...
                                       'recommendation', sprintf('%s allocated to %s (ETA: %ds, Bat: %.0f%%)', assignedDrone.name, targetVictim.name, estArrivalSec, assignedDrone.battery), ...
                                       'scores', scores, 'estimated_arrival_sec', estArrivalSec, ...
                                       'road_blocked', roadBlocked, 'selected_ground_route', selectedRoute, ...
                                       'step', step, 'timestamp', timestamp), ...
            'mission', struct('id', sprintf('M-%03d', targetVictim.id), 'status', targetVictim.status, ...
                              'targetVictim', targetVictim.id, 'assignedDrone', assignedDrone.id, ...
                              'estTime', sprintf('%d sec', estArrivalSec), 'distance', sprintf('%.1f m', assignedDistance)), ...
            'routes', struct('selected', selectedRoute, 'road_blocked', roadBlocked, ...
                             'shortest_distance', '1.8 km', 'shortest_time', '8 min', ...
                             'fastest_distance', '2.4 km', 'fastest_time', '6 min', ...
                             'alternative_distance', '3.1 km', 'alternative_time', '11 min'), ...
            'analytics', struct('rescued_count', rescuedCount, 'active_missions', 1, ...
                                'avg_response_time', sprintf('%d sec', estArrivalSec), 'success_rate', '98%'), ...
            'road_blocked', roadBlocked, ...
            'alerts', { { struct('type', 'INFO', 'title', sprintf('%s DISPATCHED', assignedDrone.name), 'message', 'Telemetry active', 'time', 'Live') } }, ...
            'simulation_step', step, ...
            'timestamp', timestamp ...
        );

        % Atomic File Persistence
        jsonStr = jsonencode(outputStruct);
        fid = fopen(tempFile, 'w');
        if fid ~= -1
            fwrite(fid, jsonStr, 'char');
            fclose(fid);
            movefile(tempFile, outputFile, 'f');
        end

        % WebSocket API Post (if backend is listening)
        try
            opts = weboptions('MediaType', 'application/json', 'Timeout', 0.5, 'RequestMethod', 'post');
            webwrite('http://localhost:5000/api/simulation-data', outputStruct, opts);
        catch
        end

        pause(loopDelay);
    end
end
